### ISSUE TITLE
Re-enable MacOS CI

### ISSUE THREAD

**Issue by johnkerl** [TileDB-Inc/TileDB-Cloud-R#121]
Status: https://cloud.r-project.org/bin/macosx/R-latest.pkg is 404ing at
https://github.com/TileDB-Inc/TileDB-Cloud-R/actions/runs/4773211148/jobs/8486156998?pr=120 for #120

And at https://cloud.r-project.org/bin/macosx/ I do see

> R 4.3.0 "Already Tomorrow" released on 2023/04/21

which seems like a wet-paint issue -- we can re-try MacOS CI soon to see if this auto-resolves, or push through the R community for resolution.

**Comment by eddelbuettel** [comment]
There is probably a way somewhere to force an R version for CI.  But just waiting a week or so should do.  Builder will catch up.
